# Generated by Django 4.0.4 on 2022-04-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('google_maps_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=16, unique=True, verbose_name='ID')),
                ('tg_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram nomi (@username)')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ismi')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiyasi')),
                ('step', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram profil',
                'verbose_name_plural': 'Telegram profillar',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appeal')),
            ],
        ),
        migrations.AddField(
            model_name='appeal',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile'),
        ),
    ]
