# Generated by Django 4.0.4 on 2022-04-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appeal_options_alter_photo_options_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon raqami'),
        ),
    ]
