# Generated by Django 4.0.4 on 2022-04-19 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appeal_comment_alter_appeal_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.appeal'),
        ),
    ]
